language: csharp

env:
  global:
    - EnableNuGetPackageRestore=true
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "kC7O0CWm9h4g+tzCwhIZEGwcdiLrb1/1PijeOKGbIWGuWS7cIksAkj2tRNMgtxxcE9CFQr8W7xDv2YzflCIlqN1nGkFjbyD4CrNg6+V1j0fZjPOQ6ssdBBVPrfrvecsAUJ0/48Tqa9VTkEpZSlwOF/VS1sO2ob36FVyWjtxvG9s="

git:
  # we need recursive init
  submodules: false

cache: apt

solution: DkimSigner.sln

script:
- xbuild DkimSigner.sln /p:Configuration="Ex2007 SP3"
- xbuild DkimSigner.sln /p:Configuration="Ex2007 SP3 RU21"
- xbuild DkimSigner.sln /p:Configuration="Ex2010"
- xbuild DkimSigner.sln /p:Configuration="Ex2010 SP1"
- xbuild DkimSigner.sln /p:Configuration="Ex2010 SP2"
- xbuild DkimSigner.sln /p:Configuration="Ex2010 SP3"
- xbuild DkimSigner.sln /p:Configuration="Ex2013"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 CU1"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 CU2"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 CU3"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU4"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU5"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU6"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU7"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU8"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU9"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU10"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU16"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU17"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU18"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU19"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU20"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU21"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU22"
- xbuild DkimSigner.sln /p:Configuration="Ex2013 SP1 CU23"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU1"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU2"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU3"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU4"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU5"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU6"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU7"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU8"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU9"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU10"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU11"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU12"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 CU13"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 Preview"
- xbuild DkimSigner.sln /p:Configuration="Ex2016 RTM"
- xbuild DkimSigner.sln /p:Configuration="Ex2019 Preview"
- xbuild DkimSigner.sln /p:Configuration="Ex2019 RTM"
- xbuild DkimSigner.sln /p:Configuration="Ex2019 CU1"
- xbuild DkimSigner.sln /p:Configuration="Ex2019 CU2"
- xbuild DkimSigner.sln /p:Configuration="Release"

#addons:
#  coverity_scan:
#    project:
#      name: "Pro/dkim-exchange"
#      description: "Build submitted via Travis CI"
#    notification_email: git@s.profanter.me
#    build_command_prepend: "xbuild /t:CleanAll travis.proj"
#    build_command:   "xbuild /t:Build travis.proj"
#    branch_pattern: coverity_scan
