language: csharp

env:
  global:
    - EnableNuGetPackageRestore=true
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "kC7O0CWm9h4g+tzCwhIZEGwcdiLrb1/1PijeOKGbIWGuWS7cIksAkj2tRNMgtxxcE9CFQr8W7xDv2YzflCIlqN1nGkFjbyD4CrNg6+V1j0fZjPOQ6ssdBBVPrfrvecsAUJ0/48Tqa9VTkEpZSlwOF/VS1sO2ob36FVyWjtxvG9s="

#  matrix:
#    - MONO_VERSION="3.10.0"

git:
  # we need recursive init
  submodules: false

mono:
  - 3.10.0	

before_install:
  - git submodule update --init --recursive

solution: DkimSigner.sln

install:
  - nuget # lets get version number
  - nuget restore DkimSigner.sln -Verbosity detailed
#  - nuget update src/Backoff.sln -Verbosity detailed
  # Fetch Mono
#  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
#  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
  - xbuild travis.proj

#addons:
#  coverity_scan:
#    project:
#      name: "Pro/dkim-exchange"
#      description: "Build submitted via Travis CI"
#    notification_email: git@s.profanter.me
#    build_command_prepend: "xbuild /t:CleanAll travis.proj"
#    build_command:   "xbuild /t:Build travis.proj"
#    branch_pattern: coverity_scan
